/*
 * Copyright 2000-2013 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package org.vaadin.netbeans.maven.editor.completion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collections;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 * @author denis
 */
class LicenseUrlConfirmationPanel extends JPanel {

    LicenseUrlConfirmationPanel( String name, String url, final JButton button )
    {
        myLicenseName = name;
        myLicenseUrl = url;
        initComponents();

        myConfirmation.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed( ActionEvent e ) {
                button.setEnabled(myConfirmation.isSelected());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmLbl = new javax.swing.JLabel();
        myConfirmation = new javax.swing.JCheckBox();
        myUrl =
                LicenseSelectPanel.getLinksComponent(
                        Collections.singletonMap(myLicenseName, myLicenseUrl),
                        this);

        org.openide.awt.Mnemonics.setLocalizedText(confirmLbl,
                org.openide.util.NbBundle.getMessage(
                        LicenseUrlConfirmationPanel.class,
                        "LBL_UrlConfirmationInfo")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(myConfirmation,
                org.openide.util.NbBundle.getMessage(
                        LicenseUrlConfirmationPanel.class, "LBL_Confirmation")); // NOI18N

        myUrl.setEditable(false);
        myUrl.setBorder(null);
        myUrl.setContentType("text/html"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(confirmLbl)
                                                .addGroup(
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        myUrl,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        317,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0,
                                                                        0,
                                                                        Short.MAX_VALUE))
                                                .addGroup(
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addGap(0,
                                                                        0,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(
                                                                        myConfirmation)))
                                .addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(confirmLbl,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(myUrl,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        24,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(myConfirmation)
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        confirmLbl.getAccessibleContext().setAccessibleName(
                org.openide.util.NbBundle.getMessage(
                        LicenseUrlConfirmationPanel.class,
                        "ACSN_ConfirmationInfo")); // NOI18N
        confirmLbl.getAccessibleContext().setAccessibleDescription(
                org.openide.util.NbBundle.getMessage(
                        LicenseUrlConfirmationPanel.class,
                        "ACSD_ConfirmationInfo")); // NOI18N
        myConfirmation.getAccessibleContext()
                .setAccessibleName(
                        org.openide.util.NbBundle.getMessage(
                                LicenseUrlConfirmationPanel.class,
                                "ACSN_Confirmation")); // NOI18N
        myConfirmation.getAccessibleContext().setAccessibleDescription(
                org.openide.util.NbBundle.getMessage(
                        LicenseUrlConfirmationPanel.class, "ACSD_Confirm")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmLbl;

    private javax.swing.JCheckBox myConfirmation;

    private javax.swing.JEditorPane myUrl;

    // End of variables declaration//GEN-END:variables

    private String myLicenseName;

    private String myLicenseUrl;
}
