/*
 * Copyright 2000-2013 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.vaadin.netbeans.editor.analyzer.ui;

import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 * @author denis
 */
public class ClientConnectPanel extends JPanel {

    public ClientConnectPanel( List<String> components ) {
        initComponents();

        myComponent.setModel(new DefaultComboBoxModel<>(components
                .toArray(new String[components.size()])));
    }

    public String getComponent() {
        if (myComponent.getSelectedItem() == null) {
            return null;
        }
        return myComponent.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componentLbl = new javax.swing.JLabel();
        myComponent = new javax.swing.JComboBox();

        componentLbl.setLabelFor(myComponent);
        org.openide.awt.Mnemonics.setLocalizedText(componentLbl,
                org.openide.util.NbBundle.getMessage(ClientConnectPanel.class,
                        "LBL_SelectClientConnector")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(componentLbl)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(myComponent, 0, 273,
                                        Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(componentLbl)
                                                .addComponent(
                                                        myComponent,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        componentLbl.getAccessibleContext().setAccessibleName(
                org.openide.util.NbBundle.getMessage(ClientConnectPanel.class,
                        "ACSN_SelectClientConnector")); // NOI18N
        componentLbl.getAccessibleContext().setAccessibleDescription(
                org.openide.util.NbBundle.getMessage(ClientConnectPanel.class,
                        "ACSD_SelectClientConnector")); // NOI18N
        myComponent.getAccessibleContext().setAccessibleName(
                componentLbl.getAccessibleContext().getAccessibleName());
        myComponent.getAccessibleContext().setAccessibleDescription(
                componentLbl.getAccessibleContext().getAccessibleDescription());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel componentLbl;

    private javax.swing.JComboBox myComponent;
    // End of variables declaration//GEN-END:variables
}
