/*
 * Copyright 2000-2013 Vaadin Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package org.vaadin.netbeans.editor.analyzer.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * @author denis
 */
public class ConnectorPanel extends JPanel {

    public ConnectorPanel( String connector,
            final Map<String, String> connectorSupers, String widget )
    {
        initComponents();

        if (widget != null) {
            mySuperclass.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed( ActionEvent e ) {
                    myWidgetSuperclass.setText(connectorSupers
                            .get(getConnectorSuperClass()));
                }
            });
            myWidgetName.setText(widget);
        }
        else {
            myWidgetName.setVisible(false);
            widgetNameLbl.setVisible(false);
            myWidgetSuperclass.setVisible(false);
            widgetSuperclassLbl.setVisible(false);
        }

        myName.setText(connector);
        mySuperclass.setModel(new DefaultComboBoxModel<>(connectorSupers
                .keySet().toArray(new String[connectorSupers.size()])));
        mySuperclass.setSelectedIndex(0);

        selectText();
    }

    public String getConnectorName() {
        return myName.getText().toString().trim();
    }

    public String getConnectorSuperClass() {
        Object selected = mySuperclass.getSelectedItem();
        if (selected == null) {
            return null;
        }
        return selected.toString();
    }

    public String getWidgetName() {
        return myWidgetName.getText().trim();
    }

    public String getWidgetSuperclass() {
        return myWidgetSuperclass.getText().trim();
    }

    private void selectText() {
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                if (SwingUtilities.getWindowAncestor(ConnectorPanel.this) == null)
                {
                    selectText();
                }
                else {
                    myName.requestFocusInWindow();
                    myName.selectAll();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myName = new javax.swing.JTextField();
        nameLbl = new javax.swing.JLabel();
        superClassLbl = new javax.swing.JLabel();
        mySuperclass = new javax.swing.JComboBox();
        widgetNameLbl = new javax.swing.JLabel();
        myWidgetName = new javax.swing.JTextField();
        widgetSuperclassLbl = new javax.swing.JLabel();
        myWidgetSuperclass = new javax.swing.JTextField();

        nameLbl.setLabelFor(myName);
        org.openide.awt.Mnemonics.setLocalizedText(nameLbl,
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "LBL_ConnectorName")); // NOI18N

        superClassLbl.setLabelFor(mySuperclass);
        org.openide.awt.Mnemonics.setLocalizedText(superClassLbl,
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "LBL_ConnectorSuperclass")); // NOI18N

        widgetNameLbl.setLabelFor(myWidgetName);
        org.openide.awt.Mnemonics.setLocalizedText(widgetNameLbl,
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "LBL_WidgetName")); // NOI18N

        widgetSuperclassLbl.setLabelFor(myWidgetSuperclass);
        org.openide.awt.Mnemonics.setLocalizedText(widgetSuperclassLbl,
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "LBL_WidgetSuperclass")); // NOI18N

        myWidgetSuperclass.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nameLbl)
                                                .addComponent(superClassLbl)
                                                .addComponent(widgetNameLbl)
                                                .addComponent(
                                                        widgetSuperclassLbl))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(
                                                        myName,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        350, Short.MAX_VALUE)
                                                .addComponent(
                                                        mySuperclass,
                                                        0,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                .addComponent(myWidgetName)
                                                .addComponent(
                                                        myWidgetSuperclass))
                                .addContainerGap()));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(nameLbl)
                                                .addComponent(
                                                        myName,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(superClassLbl)
                                                .addComponent(
                                                        mySuperclass,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(
                                                        myWidgetName,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(widgetNameLbl))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(
                                                        widgetSuperclassLbl)
                                                .addComponent(
                                                        myWidgetSuperclass,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        myName.getAccessibleContext().setAccessibleName(
                nameLbl.getAccessibleContext().getAccessibleName());
        myName.getAccessibleContext().setAccessibleDescription(
                nameLbl.getAccessibleContext().getAccessibleDescription());
        nameLbl.getAccessibleContext().setAccessibleName(
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "ACSN_ConnectorName")); // NOI18N
        nameLbl.getAccessibleContext().setAccessibleDescription(
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "ACSD_ConnectorName")); // NOI18N
        superClassLbl.getAccessibleContext().setAccessibleName(
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "ACSN_ConnectorSuperclass")); // NOI18N
        superClassLbl.getAccessibleContext().setAccessibleDescription(
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "ACSD_ConnctorSuperclass")); // NOI18N
        mySuperclass.getAccessibleContext().setAccessibleName(
                superClassLbl.getAccessibleContext().getAccessibleName());
        mySuperclass.getAccessibleContext()
                .setAccessibleDescription(
                        superClassLbl.getAccessibleContext()
                                .getAccessibleDescription());
        widgetNameLbl.getAccessibleContext().setAccessibleName(
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "ACSN_WidgetName")); // NOI18N
        widgetNameLbl.getAccessibleContext().setAccessibleDescription(
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "ACSD_WidgetName")); // NOI18N
        widgetSuperclassLbl.getAccessibleContext().setAccessibleName(
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "ACSN_WidgetSuperclass")); // NOI18N
        widgetSuperclassLbl.getAccessibleContext().setAccessibleDescription(
                org.openide.util.NbBundle.getMessage(ConnectorPanel.class,
                        "ACSD_WidgetSuperclass")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField myName;

    private javax.swing.JComboBox mySuperclass;

    private javax.swing.JTextField myWidgetName;

    private javax.swing.JTextField myWidgetSuperclass;

    private javax.swing.JLabel nameLbl;

    private javax.swing.JLabel superClassLbl;

    private javax.swing.JLabel widgetNameLbl;

    private javax.swing.JLabel widgetSuperclassLbl;
    // End of variables declaration//GEN-END:variables
}
