package org.vaadin.netbeans.editor.analyzer;

import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 * @author denis
 */
class ThemePanel extends JPanel {

    public ThemePanel( String theme ) {
        initComponents();

        myThemeName.setText(theme);

        selectText();
    }

    String getThemeName() {
        return myThemeName.getText().trim();
    }

    private void selectText() {
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                if (SwingUtilities.getWindowAncestor(ThemePanel.this) == null) {
                    selectText();
                }
                else {
                    myThemeName.requestFocusInWindow();
                    myThemeName.selectAll();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        myThemeName = new javax.swing.JTextField();

        nameLbl.setLabelFor(myThemeName);
        org.openide.awt.Mnemonics.setLocalizedText(nameLbl, org.openide.util.NbBundle.getMessage(ThemePanel.class, "LBL_ThemeName")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myThemeName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(myThemeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nameLbl.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ThemePanel.class, "ACSN_ThemeName")); // NOI18N
        nameLbl.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(ThemePanel.class, "ACSD_ThemeName")); // NOI18N
        myThemeName.getAccessibleContext().setAccessibleName(nameLbl.getAccessibleContext().getAccessibleName());
        myThemeName.getAccessibleContext().setAccessibleDescription(nameLbl.getAccessibleContext().getAccessibleDescription());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField myThemeName;
    private javax.swing.JLabel nameLbl;
    // End of variables declaration//GEN-END:variables
}
